### PR TITLE
Tag SecurityMonkey as deprecated

### PR DESCRIPTION
**Pull request by philipmeadows**
SecurityMonkey is in maintenance mode and will be EOL in 2020. It shouldn't be recommended.

### CODE REVIEW

**Comment by 0xdabbad00** [comment]
I don't think this list recommends any of these tools.  It's just listing them.  If you want to get rid of, or maybe mark as deprecated, tools that no longer are maintained, there are some others:
- Krampus (is based on Security Monkey)
- probably half of the S3 bucket finding tools, if nothing else these are just duplicating each other
- cloudjack and cloudfrunt as the issue they work with has been fixed
- weirdAAL (questionable as to if it is maintained still)

**Comment by philipmeadows** [comment]
I think it would be useful to at least mark them as deprecated.

**Comment by philipmeadows** [comment]
Or maybe move to a different section?

**Comment by toniblyx** [comment]
Thanks for your suggestion @philipmeadows, I agree with @0xdabbad00, this list doesn't recommend any tool but it definitely would help others to say that is deprecated. There are other deprecated tools as well but I'm not 100% sure of that so I think the best way to list them is probably adding some metadata like: stars, last commit date, contributors, open issues, etc. Just to show how active each project is. WDYT?

**Comment by philipmeadows** [comment]
That sounds like a good longer term plan, maybe just add [DEPRECATED] (or something like that) to the ones that we know are deprecated would be a good start?

**Review by toniblyx — APPROVED** [review]
Thanks @philipmeadows

**Comment by toniblyx** [comment]
Changed title for obvious reasons, not removing it.

**Pull request merged**
